name: Feature CI

on:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  linux:
    name: Linux build + tests
    uses: ./.github/workflows/feature-linux.yml

  windows:
    name: Windows build + tests
    uses: ./.github/workflows/feature-windows.yml
